# Generated by Django 2.1.7 on 2019-02-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('userId', models.IntegerField(max_length=256)),
                ('id', models.IntegerField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=256)),
            ],
        ),
    ]
