# Generated by Django 2.1.7 on 2019-02-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190226_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
