# Generated by Django 2.1.7 on 2019-02-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
