# Generated by Django 2.1.7 on 2019-02-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190227_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default='_BwX2kbspp5Xzf5-0419M', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
