# Generated by Django 2.1.7 on 2019-02-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190227_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default='Srmn8fymcHo5ScuqQ-unf', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
