# Generated by Django 2.1.7 on 2019-02-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190227_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default='cZVaQRkoS7_hghFXy2rjC', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
