# Generated by Django 2.1.7 on 2019-02-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='wfYDS9BWw8o04Ye173uUO', max_length=21, primary_key=True, serialize=False),
        ),
    ]
