# Generated by Django 2.1.7 on 2019-02-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_auto_20190226_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='X6hM392D2_fQ2pnLsAurT', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
