# Generated by Django 2.1.7 on 2019-02-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_auto_20190226_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='brF4FWe6iSZ1tXvcovKg-', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
