# Generated by Django 2.1.7 on 2019-02-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0009_auto_20190227_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='FM-n4CtEDV5oevErvdKvk', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
