# Generated by Django 2.1.7 on 2019-02-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0010_auto_20190227_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='-k8FGQe3TNr_ANDZn_mPS', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
