# Generated by Django 2.1.7 on 2019-02-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0012_auto_20190227_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='p17782CcvVv4puz5-ysgg', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
