# Generated by Django 2.1.7 on 2019-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0014_auto_20190227_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='8BZkV7W4x9D2CGQGFYrE4', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
