# Generated by Django 2.1.7 on 2019-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0016_auto_20190306_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='JCNaNfCOl2xcmhy62nuMc', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
