# Generated by Django 2.1.7 on 2019-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0017_auto_20190306_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='EOn63e2jGuvz8XI-4dN8j', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
