# Generated by Django 2.1.7 on 2019-02-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0006_auto_20190227_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default='pkr80U6m8ap18Xxg2CL3B', editable=False, max_length=21, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
