# Generated by Django 2.1.7 on 2019-02-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190227_0303'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='xAx3tTi6ULjfhSwT62QhO', editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
