# Generated by Django 2.1.7 on 2019-02-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190227_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
